<?php

$Parameter_AppSiteID = "2";
$Parameter_Debug = "1";

$Parameter_AppName = "Hubara";
$Parameter_AppTitle = "NWAS Hubara";
$Parameter_URL = "https://Hubara.dev.dev.NorthWestAmbulance.nhs.uk/";
$Parameter_Description = "Canary & Development Channel";
$Parameter_Channel = "Development";
$Parameter_Background = "#e4deff";

$Parameter_Author = "NWAS (https://nwas.nhs.uk/)";
$Parameter_Contact = "Hubara.Admin@nwas.nhs.uk";
$Parameter_Corp = "North West Ambulance Service NHS Trust";
$Parameter_CorpShortHand = "NWAS";
$Parameter_Copyright = "&copy; 2021 North West Ambulance Service NHS Trust";
$Parameter_AppLogo = "Corp_Logo.png";

$Parameter_SQL_ServerName = "EPDEV01.NorthWestAmbulance.nhs.uk";
$Parameter_SQL_Database = "Hubara - Development";
$Parameter_SQL_UserID = "Hubara-Resources";
$Parameter_SQL_Password = "jfghjf6r5twseagty45SDFEWsr#d";

$Parameter_SQL_C3_ServerName = "EHSQL01.NorthWestAmbulance.nhs.uk";
$Parameter_SQL_C3_Database = "MIS_C3_Data";
$Parameter_SQL_C3_Resources_Data = "Resource_Data";

?>